// Mock character data - using picsum for placeholder images
export const characters = [
  {
    id: 1,
    name: "Kay",
    username: "@akash258",
    bio: "kAYYY",
    tags: ["Female", "Adventure", "AI Assistant"],
    extraTags: 2,
    comments: 1,
    rating: 3.0,
    ratingCount: 1,
    image: "https://picsum.photos/seed/kay1/300/400",
    nsfw: false,
  },
  {
    id: 2,
    name: "Jasmine",
    username: "@akash258",
    bio: "Hi, I am Jasmine.",
    tags: ["Friend", "Female", "Adventure"],
    extraTags: 4,
    comments: 0,
    rating: 1.4,
    ratingCount: 2,
    image: "https://picsum.photos/seed/jasmine2/300/400",
    nsfw: false,
  },
  {
    id: 3,
    name: "dobby",
    username: "@shiny_swan_136",
    bio: "snjfklsdnklfnklann,",
    tags: ["NSFW", "Female", "Male", "Adventure"],
    extraTags: 6,
    comments: 2,
    rating: 0.0,
    ratingCount: 0,
    image: "https://picsum.photos/seed/dobby3/300/400",
    nsfw: true,
  },
  {
    id: 4,
    name: "nimbaaa",
    username: "@shiny_swan_136",
    bio: "bvvghvhbjhb",
    tags: ["Male", "Female", "Action", "Age Play"],
    extraTags: 7,
    comments: 1,
    rating: 0.0,
    ratingCount: 0,
    image: "https://picsum.photos/seed/nimbaaa4/300/400",
    nsfw: false,
  },
  {
    id: 5,
    name: "Nova Byte",
    username: "@gentle_panda_327",
    bio: "Nova is a witty AI hacker from the near future who loves...",
    tags: ["Male", "Adventure", "Action"],
    extraTags: 3,
    comments: 0,
    rating: 4.5,
    ratingCount: 12,
    image: "https://picsum.photos/seed/nova5/300/400",
    nsfw: false,
  },
  {
    id: 6,
    name: "Rose",
    username: "@akash258",
    bio: "welcome, cutie-sweetie fox",
    tags: ["Female", "Romance", "Adventure"],
    extraTags: 2,
    comments: 3,
    rating: 4.8,
    ratingCount: 5,
    image: "https://picsum.photos/seed/rose6/300/400",
    nsfw: false,
  },
  {
    id: 7,
    name: "Ironman",
    username: "@dawdawdaw",
    bio: "Ironman is a high-intelligence",
    tags: ["Male", "Action", "Adventure"],
    extraTags: 5,
    comments: 4,
    rating: 4.9,
    ratingCount: 20,
    image: "https://picsum.photos/seed/ironman7/300/400",
    nsfw: false,
  },
  {
    id: 8,
    name: "axa",
    username: "@gentle_panda_327",
    bio: "axa is your loyal companion",
    tags: ["Male", "Adventure"],
    extraTags: 1,
    comments: 0,
    rating: 3.5,
    ratingCount: 3,
    image: "https://picsum.photos/seed/axa8/300/400",
    nsfw: false,
  },
  {
    id: 9,
    name: "Nick",
    username: "@bouncy_ruby_633",
    bio: "Nick",
    tags: ["Male", "Action"],
    extraTags: 0,
    comments: 0,
    rating: 0.0,
    ratingCount: 0,
    image: "https://picsum.photos/seed/nick9/300/400",
    nsfw: false,
  },
  {
    id: 10,
    name: "Doggy",
    username: "@mikasingh",
    bio: "I am a good boy!",
    tags: ["Adventure"],
    extraTags: 0,
    comments: 1,
    rating: 5.0,
    ratingCount: 2,
    image: "https://picsum.photos/seed/doggy10/300/400",
    nsfw: false,
  },
  {
    id: 11,
    name: "Luna",
    username: "@starlight_99",
    bio: "Luna is mysterious and wise",
    tags: ["Female", "Adventure", "Mystery"],
    extraTags: 3,
    comments: 5,
    rating: 4.7,
    ratingCount: 8,
    image: "https://picsum.photos/seed/luna11/300/400",
    nsfw: false,
  },
  {
    id: 12,
    name: "Rex",
    username: "@fire_wolf_22",
    bio: "Strong, brave, and fearless warrior",
    tags: ["Male", "Action", "Adventure"],
    extraTags: 2,
    comments: 2,
    rating: 4.2,
    ratingCount: 7,
    image: "https://picsum.photos/seed/rex12/300/400",
    nsfw: false,
  },
];

export const categories = [
  "AI Assistant", "Action", "Adventure", "Age Play", "Anal",
  "Anime", "Anthro", "Bondage", "Cheating", "Chubby",
  "Comedy", "Corruption"
];

export const navTabs = ["All", "Following", "New", "Popular"];
